spring.application.name=credit-card-payment-system
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=credit-card-db

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

stripe.api.key=${STRIPE_API_KEY}
stripe.secretKey=${STRIPE_SECRET_KEY}

external.gemini.api.key=${EXTERNAL_GEMINI_API_KEY}
